apiVersion: v1
kind: ConfigMap
metadata:
  name: event-management-config
  namespace: event-management
data:
  # MySQL config (Common user)
  MYSQL_USER: "root"
  MYSQL_DB_BOOKING: "booking_db"
  MYSQL_DB_USER: "users"
  MYSQL_DB_PAYMENT: "payment_service"
  MYSQL_HOST: "db-mysql"

  # PostgreSQL config (Common user)
  POSTGRES_USER: "postgres"
  POSTGRES_DB_EVENT: "event_db"
  POSTGRES_DB_TICKET: "ticket_db"
  POSTGRES_DB_NOTIFICATION: "notifications"
  POSTGRES_HOST: "db-postgres"
  
  # External URLs used by services to communicate internally
  EVENT_SERVICE_URL: "http://event-service.event-management.svc.cluster.local:8000/events"
  PAYMENT_SERVICE_URL: "http://payment-service.event-management.svc.cluster.local:8000/payments"
  
  # RabbitMQ Configurations
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_QUEUE: "notifications"

  # Misc
  ALGORITHM: "HS256"
