apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres
  namespace: event-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: event-management-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-management-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/init-postgres.sql
              subPath: init-postgres.sql
      volumes:
        - name: init-scripts
          configMap:
            name: db-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres
  namespace: event-management
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db-postgres
