apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: event-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: aravindroy1/bookingservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: event-management-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-management-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-management-config
                  key: MYSQL_HOST
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: event-management-config
                  key: MYSQL_DB_BOOKING
            - name: EVENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: event-management-config
                  key: EVENT_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: event-management-config
                  key: PAYMENT_SERVICE_URL
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-management-config
                  key: RABBITMQ_HOST
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: event-management-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: event-management
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30003
  selector:
    app: booking-service
