apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: event-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: aravindroy1/payment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: event-management-secrets
                  key: MYSQL_DATABASE_URL_PAYMENT
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: event-management-secrets
                  key: RABBITMQ_URL
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: event-management
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30004
  selector:
    app: payment-service
