apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: event-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: aravindroy1/notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-management-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: event-management-config
                  key: RABBITMQ_QUEUE
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: event-management-secrets
                  key: EMAIL_USER
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-management-secrets
                  key: EMAIL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: event-management
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30005
  selector:
    app: notification-service
