apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-generator
  namespace: event-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-generator
  template:
    metadata:
      labels:
        app: ticket-generator
    spec:
      containers:
        - name: ticket-generator
          image: aravindroy1/ticket-generator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: event-management-secrets
                  key: POSTGRES_DATABASE_URL_TICKET
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: event-management-secrets
                  key: RABBITMQ_URL
          volumeMounts:
            - name: qr-codes
              mountPath: /service/qr_codes
      volumes:
        - name: qr-codes
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-generator
  namespace: event-management
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30006
  selector:
    app: ticket-generator
